### ISSUE TITLE
components/organisms/ListTabの単体テストの作成

### ISSUE THREAD

**Issue by FAL-coffee** [FAL-coffee/hacker-class-room#152]

**Comment by tejeshatr** [comment]
I'm interested in the project, Can you explain the issue in English?

**Comment by FAL-coffee** [comment]
Thanks for your interest in this project!
Since I am not fluent in English, I will describe the translated text at DeepL. I apologize if there are any strange parts.
This project is to develop a community service for student engineers called **Hakacla** (Hacker class room).

And about this Issue, the unit test in components/organisms/ListTab (ListTab/test.tsx) currently only implements the render test.
I would like to implement a code to pass the fixture data to the component like stories and make sure that the data is passed correctly and that tabs are generated for the length of the tabs props.

Would be glad if you could join the project. Thank you for your time.
